# Generated by Django 3.1.2 on 2020-11-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_tbl_workflow_level_data_details_tbl_workflow_level_data_mst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_Transaction_Type_Mst',
        ),
    ]
