# Generated by Django 3.1.2 on 2020-11-17 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_delete_tbl_transaction_type_mst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Transaction_Type_Mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('transaction_name', models.CharField(max_length=20, verbose_name='Transaction Name')),
                ('is_accounting_required', models.CharField(default='N', max_length=1, verbose_name='Is Accounting Required')),
                ('tbl_transaction_header', models.CharField(max_length=100, verbose_name='Transaction Header Table Name')),
                ('tbl_transaction_details', models.CharField(max_length=100, verbose_name='Transaction Details Name')),
                ('tbl_transaction_header_field', models.CharField(max_length=100, verbose_name='Transaction Header Field Name')),
                ('tbl_transaction_details_field', models.CharField(max_length=100, verbose_name='Transaction Details Field Name')),
                ('join_condition', models.TextField(verbose_name='Join Condition')),
                ('tbl_accounting', models.CharField(max_length=100, verbose_name='Accounting Table Name')),
                ('tbl_sub_accounting_summary', models.CharField(max_length=100, verbose_name='Accounting Table Name')),
                ('ref_id_2_column', models.CharField(max_length=40, verbose_name='Reference Id 2 Coloumn Name')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
            ],
        ),
    ]
