# Generated by Django 3.1.2 on 2020-11-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_tbl_transaction_type_mst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_transaction_type_mst',
            old_name='ref_id_2_column',
            new_name='ref_id_2_coloumn_name',
        ),
        migrations.RenameField(
            model_name='tbl_transaction_type_mst',
            old_name='tbl_sub_accounting_summary',
            new_name='tbl_sub_accounting',
        ),
    ]
