# Generated by Django 3.1.2 on 2020-11-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_auto_20201117_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_assign_pages_roles',
            name='company_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id'),
        ),
        migrations.AlterField(
            model_name='tbl_transaction_type_mst',
            name='is_accounting_required',
            field=models.BooleanField(default=False, verbose_name='Is Accounting Required'),
        ),
    ]
