# Generated by Django 3.1.2 on 2020-11-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_auto_20201120_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_transaction_type_mst',
            name='ref_id_2_coloumn_name',
        ),
        migrations.RemoveField(
            model_name='tbl_transaction_type_mst',
            name='tbl_sub_accounting',
        ),
    ]
