# Generated by Django 3.1.2 on 2020-11-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_auto_20201120_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_employee_mst',
            name='employee_seq_no',
            field=models.CharField(max_length=40, verbose_name='Employee Seq No'),
        ),
    ]
