# Generated by Django 3.1.2 on 2020-11-23 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0051_auto_20201123_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_login_mst',
            name='user',
            field=models.OneToOneField(default=0, max_length=140, on_delete=django.db.models.deletion.CASCADE, related_name='userRow', to=settings.AUTH_USER_MODEL),
        ),
    ]
