# Generated by Django 3.0.8 on 2020-12-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0052_auto_20201123_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_source_details',
            name='field_length',
            field=models.CharField(max_length=20, verbose_name='Field Length'),
        ),
        migrations.AlterField(
            model_name='tbl_sourcetable_fields_mst',
            name='field_length',
            field=models.CharField(max_length=20, verbose_name='Field Length'),
        ),
        migrations.DeleteModel(
            name='tbl_workflow_level_data_details',
        ),
        migrations.DeleteModel(
            name='tbl_workflow_level_data_mst',
        ),
    ]
