# Generated by Django 3.1.2 on 2020-12-11 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_tbl_workflow_level_data_mst'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workflow_level_data_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('sequence_number', models.IntegerField(default=0, verbose_name='Sequence Number')),
                ('next_sequence_number', models.IntegerField(default=0, verbose_name='Next Sequence Number')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('action_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_action_mst', verbose_name='Action Ref Id')),
                ('activity_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_activity_mst', verbose_name='Activity Ref Id')),
                ('header_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='workflowLevelDetailsRow', to='portal.tbl_workflow_level_data_mst', verbose_name='Header Ref ID')),
            ],
        ),
    ]
