# Generated by Django 3.1.2 on 2020-12-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0055_tbl_workflow_level_data_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_workflow_mst',
            name='company_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id'),
        ),
        migrations.AddField(
            model_name='tbl_workflow_mst',
            name='entity_ref_id',
            field=models.TextField(default=0, verbose_name='Entity Ref ID'),
        ),
        migrations.AddField(
            model_name='tbl_workflow_mst',
            name='level_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_level_data_mst', verbose_name='Level Ref Id'),
        ),
        migrations.AddField(
            model_name='tbl_workflow_mst',
            name='share_id',
            field=models.IntegerField(default=0, verbose_name='Share ID'),
        ),
        migrations.AddField(
            model_name='tbl_workflow_mst',
            name='workflow_type_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Workflow Type Ref Id'),
        ),
    ]
