# Generated by Django 3.1.2 on 2020-12-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0058_auto_20201211_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_workflow_mst',
            name='company_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id'),
        ),
    ]
