# Generated by Django 3.1.2 on 2020-12-11 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0059_auto_20201211_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workflow_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_amount', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Approval Amount')),
                ('is_approval_required', models.BooleanField()),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('currency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.tbl_currency_mst')),
                ('field_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_level_data_details', verbose_name='field Name')),
                ('header_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='workflowDetailsRow', to='portal.tbl_workflow_mst', verbose_name='Header Ref ID')),
                ('level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='level_id', to='portal.tbl_workflow_level_data_details', verbose_name='Level')),
                ('screen_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='field', to='portal.tbl_workflow_level_data_details', verbose_name='Screen')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_workflow_sub_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(default=0, verbose_name='Sequence Number')),
                ('next_sequence_number', models.IntegerField(default=0, verbose_name='Next Sequence Number')),
                ('is_email_required', models.BooleanField(blank=True)),
                ('is_whatsapp_required', models.BooleanField(blank=True)),
                ('is_sms_required', models.BooleanField(blank=True)),
                ('is_reminder_required', models.BooleanField(blank=True)),
                ('is_worklist_required', models.BooleanField(blank=True)),
                ('approval_amount', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Approval Amount')),
                ('is_approval_required', models.BooleanField()),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('action_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_action_mst', verbose_name='Action Ref Id')),
                ('activity_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_activity_mst', verbose_name='Activity Ref Id')),
                ('company_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id')),
                ('currency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.tbl_currency_mst')),
                ('details_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_mst', verbose_name='Details Ref ID')),
                ('employee_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_employee_mst', verbose_name='Employee Ref Id')),
                ('header_details_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='workflowdetailsDetailsRow', to='portal.tbl_workflow_details', verbose_name='Header Ref ID')),
                ('level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_level_data_details', verbose_name='Entity Ref Id')),
                ('reminder_days', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='reminderdaysDetailsRow', to='portal.tbl_master', verbose_name='Reminder Days Ref Id')),
                ('role_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_role_mst', verbose_name='Role Ref Id')),
                ('sla_days', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sladaysDetailsRow', to='portal.tbl_master', verbose_name='SLA Days Ref Id')),
            ],
        ),
    ]
