# Generated by Django 3.1.2 on 2020-12-11 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0060_tbl_workflow_details_tbl_workflow_sub_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_workflow_level_data_mst',
            name='entity_ref_id',
            field=models.TextField(default=0, verbose_name='Entity Ref ID'),
        ),
        migrations.CreateModel(
            name='tbl_workflow_screen_linking_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('entity_ref_id', models.TextField(default=0, verbose_name='Entity Ref ID')),
                ('workflow_ref_id', models.CharField(max_length=15, verbose_name='Workflow name')),
                ('field_ref_id', models.CharField(max_length=100, verbose_name='Field Ref ID')),
                ('label_panel_ref_id', models.CharField(max_length=100, verbose_name='Label Panel Ref ID')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('company_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id')),
                ('left_panel_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_left_panel', verbose_name='Left Panel Ref Id')),
                ('level_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_workflow_level_data_mst', verbose_name='Level Ref Id')),
                ('workflow_type_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Workflow Type Ref Id')),
            ],
        ),
    ]
