# Generated by Django 3.1.2 on 2020-12-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0062_auto_20201221_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_workflow_level_data_details',
            name='level',
        ),
        migrations.AlterField(
            model_name='tbl_workflow_level_data_details',
            name='header_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initialItemRow', to='portal.tbl_workflow_level_data_mst', verbose_name='Header Ref ID'),
        ),
    ]
